# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [51]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [52]:
# Import torch
import torch

# Create random tensor
tensor_2 = torch.randn((7, 7), dtype=torch.float16)
tensor_2, tensor_2.shape, tensor_2.type

(tensor([[-0.2299, -0.9243, -1.2461, -1.3418,  0.7759, -1.7158, -0.1465],
         [ 0.5786,  1.7803,  1.1680,  0.4807, -0.7554, -0.0622, -0.3623],
         [-0.5898, -0.2423, -0.1348, -1.0977,  0.9185, -0.6709,  0.8276],
         [-0.4561,  1.0010, -2.0215, -0.6367, -0.1500, -1.3887, -1.0430],
         [-0.5850, -0.2292,  0.6299,  0.4722, -0.1482, -0.3103, -0.3613],
         [ 0.4153,  0.4319,  0.0451, -1.6191, -1.1602, -0.2168,  1.0684],
         [ 0.3706, -1.8818,  0.4980, -1.5137,  1.8662,  0.9355, -1.0869]],
        dtype=torch.float16),
 torch.Size([7, 7]),
 <function Tensor.type>)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [53]:
# Create another random tensor
tensor_3 = torch.rand((1, 7), dtype=torch.float16)
tensor_3 = tensor_3.T # Isso "Inverte a matriz"

# Perform matrix multiplication 
saida = tensor_2 @ tensor_3

saida, saida.shape

(tensor([[-2.4434],
         [ 1.6846],
         [-0.0677],
         [-2.5547],
         [-0.7002],
         [ 0.8403],
         [-0.4724]], dtype=torch.float16),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [54]:
# Set manual seed
torch.manual_seed(seed=42)

# Create two random tensors
tensor_2 = torch.randn((7, 7), dtype=torch.float16)
tensor_3 = torch.rand((7, 1), dtype=torch.float16)

# Matrix multiply tensors
saida = tensor_2 @ tensor_3

# print
saida, saida.shape

(tensor([[ 2.2207],
         [-1.3125],
         [-1.4932],
         [-0.6616],
         [-1.2637],
         [-0.9614],
         [ 0.3347]], dtype=torch.float16),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [55]:
# Set random seed on the GPU
torch.manual_seed(1234)      # Seed da CPU
torch.cuda.manual_seed(1234) # Seed da GPU


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [56]:
# Set random seed
torch.cuda.manual_seed(123)
        
# Check for access to GPU
if (torch.cuda.is_available()):
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    devide = "cpu"

# Create two random tensors on GPU
tensor_1 = torch.rand((2, 3), device=device)
tensor_2 = torch.rand((2, 3), device = device)

print(tensor_1, tensor_1.device)
print(tensor_2, tensor_2.device)

tensor([[0.0669, 0.9448, 0.2207],
        [0.2721, 0.0079, 0.7900]], device='cuda:0') cuda:0
tensor([[0.6396, 0.1476, 0.8214],
        [0.4767, 0.6468, 0.5723]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [57]:
# Perform matmul on tensor_A and tensor_B
tensor_2 = torch.reshape(tensor_2, (3, 2))
saida = tensor_1 @ tensor_2

saida, saida.shape, saida.device

(tensor([[0.9616, 0.5866],
         [0.6914, 0.4960]], device='cuda:0'),
 torch.Size([2, 2]),
 device(type='cuda', index=0))

### 8. Find the maximum and minimum values of the output of 7.

In [58]:
# Find max
max = torch.max(saida)
print(max)

# Find min
min = torch.min(saida)
print(min)

tensor(0.9616, device='cuda:0')
tensor(0.4960, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [59]:
# Find arg max
index_max = torch.argmax(saida)
print(index_max)

# Find arg min
index_min = torch.argmin(saida)
print(index_min)

# Para printar as coordenadas, usa-se os metodos de % e //

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [60]:
# Set seed
torch.manual_seed(7)
torch.cuda.manual_seed(7)

# Create random tensor
tensor = torch.rand((1, 1, 1, 7))

# Remove single dimensions
tensor_squeeze = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(tensor_squeeze, tensor_squeeze.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]]]]) torch.Size([1, 1, 1, 7])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071]) torch.Size([7])
