In [45]:
import numpy as np
import torch

torch.__version__

'2.7.1+cu126'

# Tensores

Tensores são os blocos fundamentais na construção da aprendizagem de maquina
por exemplo, pode-se representar um tensor que recebe uma imagem como [numero_de_canais, altura_da_imagem, Largura_da_imagem]. Esse tensor teria 3 dimensões.

Tensores são construidos a partir de listas do Python ou arrays numpy(melhor).


Tensor Escalar
    É um Tensor com apenas um elemento e de dimensão 0
    è instanciado com torch.tensor(value)

In [46]:
scalar = torch.tensor(12)
scalar        # tensor(12)
scalar.item() # 12
scalar.ndim   # 0 - O Tensor possui 0 dimensões

0

# Vetores

Vetores são tensores de uma unica dimensão que pode conter vários números(em resumo, é uma lista). o primeiro exemplo(o da imagem) é um vetor.

In [47]:
vetor = torch.tensor([1, 2, 3])
vetor        # tensor([1, 2, 3])
vetor.ndim   # 1 - imprime o número de dimensões do vetor
vetor.shape  # torch.Size([3]) - shape

torch.Size([3])

# Matrizes

Matrizes são basicamente vetores dentro de vetores

In [48]:
MATRIZ = torch.tensor([
    [7,  8,  9],
    [9, 10, 11]
])

MATRIZ.ndim     # 2
MATRIZ.shape    # [2, 3]

torch.Size([2, 3])

# Tensores

tensores reais são "listas" que possuem 3 dimensões ou mais

obs.: Note que matrizes e tensores sõ denotados por letras maiúsculas, enquanto escalares e vetores são denotados por letras minúsculas

<img src=00_img_apoio_01.png width=500>

In [49]:
TENSOR = torch.tensor([
    [
        [7,  8,  9],
        [9, 10, 11]
    ],
    [
        [1, 2, 3],
        [1, 2, 3]
    ]
])

TENSOR.ndim     # 3
TENSOR.shape    # [2, 2, 3]

torch.Size([2, 2, 3])

Raramente iremos criar um Tensor manualmente, como tivemos feito até agora. 

Então, oq faremos? vamos criar um tensor com números aleatórios e deixar a MAchine Learn ir ajustando os números "sozinho".

O Ideal seria começar o tensor com 0s ou 1s

Também pode-se criar tensores com números aleatórios em um intervalo X e Y

torch.arange(start, end, step)

Para fazer um Tensor com Range

In [50]:
randon_tendor = torch.rand(size=(3, 4)) # Note que esse "Tensor" na verdade é uma matriz
print(randon_tendor)

zeros = torch.zeros(size=(3, 4))
print(zeros)

ones = torch.ones(size=(3, 4))
print(ones)

T = torch.arange(1, 10)
print(T)

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


Podemos criar um tensor do tamanho de outro com 0s e 1s de forma fácil, com as funções
<ul>
    <li>zeros_like</li>
    <li>ones_like</li>
</ul>

In [51]:
zeros2 = torch.zeros_like(zeros)
print(zeros2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


<p>Não entendi muito bem, mas exietem tipos diferentes de tensores. Quando for lidar com tensores, precisamos investigar algumas de suas caracteristicas, como:</p>

<ul>
    <li>ndim</li>
    <li>shape</li>
    <li>devide - dispositivo(CPU ou GTU)</li>
</ul>

In [52]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(f"Shape of tensor:             {some_tensor.shape}")
print(f"Datatype of tensor:          {some_tensor.dtype}")
print(f"Device tensor is stored on:  {some_tensor.device}") # will default to CPU

Shape of tensor:             torch.Size([3, 4])
Datatype of tensor:          torch.float32
Device tensor is stored on:  cpu


Um modelo aprende investigando tensores e executando uma série de operações para criar uma representação dos padrões nos dados de entrada.

Essas operações costumam ser:

<ul>
    <li>Adição</li>
    <li>Subtração</li>
    <li>Multiplicação</li>
    <li>Divisão</li>
    <li>Multiplicação de matrizes</li>
</ul >

Para realizar essa operações manualmente, pode-se tratar o tensor da mesma forma que se trata um Array numpy. como:
<br>TENSOR = TENSOR * 10

É importante saber disso também:

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])

---


# Multiplicação de Matriz

É extremamente importante para o deep Learning, o Pytorch já têm uma função que faz isso, a <stronger>torch.matmul()</stronger>

Mas é importante saber as 2 regras fundamentais da multiplicação de matriz
<ol>
    <li>Os Shapes internos das Matrizes devem ter dimenções iguais</li>
    <p>Tendo 2 Matrizes, A(shape = (m, n)) e B(shape = (p, q)), a multiplização só funaionará se n == p</p>
        <ul>
            <li>(3, 2) @ (3, 2) -> não funciona</li>
            <li>(2, 3) @ (3, 2) -> funciona</li>
            <li>(3, 2) @ (2, 3) -> funciona</li>
        </ul>
    <li>O resultado da multiplicação tem a saida com as dimençoes externas da matriz</li>
        <ul>
            <li>(3, 2) @ (3, 2) -> (3, 2)</li>
            <li>(2, 3) @ (3, 2) -> (2, 2)</li>
            <li>(3, 2) @ (2, 3) -> (3, 3)</li>
        </ul>
</ol>



<img src=00_img_apoio_02.png width=800>

In [53]:
# Shapes causam erros
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B)
# Não pode multiplicar (3x2 por 3x2)

In [54]:
# Esse caso da certo
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10, 12],
                         [8, 11, 14], 
                        ], dtype=torch.float32)

torch.matmul(tensor_B, tensor_A)

tensor([[ 97., 126.],
        [111., 144.]])

Pode-se inverter as dinmeções de um Tensor facilmente utilizando o "Metodo" T.

como funciona?

M = [
        [1, 2, 3],
        [1, 2, 3]
    ]

M.T
[
    [1, 1], 
    [2, 2], 
    [3, 3]
]

In [55]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

x.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [56]:

# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match
Output:
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


Nota: uma multiplicação de matrizes é chamada de produto escalar (dot product) e são muito usadas em redes neurais

In [57]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=3) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[1.3702, 1.5487, 0.7538],
        [3.6252, 2.5165, 0.7293],
        [5.8802, 3.4843, 0.7048]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 3])


<h1>Extração de dados de um tensor</h1>

<p>Extraimos os dados do tensor com metodos iguais aos do numpy</p>

<ul>
    <li>x.min()</li>
    <li>x.max()</li>
    <li>x.type(torch.float32).mean()</li>
    <li>x.sum()</li>
    <li>x.median()</li>
    <li>torcg.argmax(x) -> index do elemento max</li>
    <li>torch.argmin(x) -> index do elemento min</li>
    
</ul>

<hr>

<h2>Tipo de dados nos Tensores</h2>

<p>Tensores de tipos diferentes(como float64 e float32) dão erro, então é necessário igualar os tipos. para isso, utilizamos a função</p>

<h4>TENSOR.type(dtype)</h4>
<p>Por exemplo tensor.type(torch.float16)</p>

In [58]:
TENSOR = torch.tensor([1, 2, 3], dtype=int)
print(TENSOR.dtype)
TENSOR = TENSOR.type(torch.float32)
print(TENSOR.dtype)

torch.int64
torch.float32


<h2>Algumas operações de tensores</h2>

<p>Em alguns momentos, será necessário modificar os tensores, modificando o seu shape e ndim, aqui vai uma lista detalhada dessas funções e oq fazem</p>

<ol>
    <li>torch.reshape(input, new_shape)</li>
        Retorna o novo tensor rearranjado<br>
        O segundo argumento é uma túpla<br>
        Não é implace<br>
        <br>
        <li>Tensor.view(shape)</li>
        Não modifica o Tensor, só serve para visualização do tensor com o shape alterado<br>
        <br>
        <li>torch.stack(Tensor, dim=0)</li>
        Empilha multiplos Tensores, criando uma nova dimenção<br>
        <br>
        <li>torch.squeeze(input)</li>
        Remove dimenções cujo tamanho é 1<br>
        por exemplo, o Tensor torch.randn(1, 3, 1, 5) termina com shape = (3, 5) após a aplicação da função.<br>
        Não é in-place<br>
        <br>
        <li>torch.permute(input, dims)</li>
        Reorganiza as dimenções do Tensor<br>
        Utiliza o index das dimenções para organizar<br>
        Ou seja, torch.permute(torch.rand(2, 3, 4), (0, 2, 1)) == tensor com shape= (2, 4, 3)<br>
</ol>

In [59]:
# torch.reshape(tensor, (new shape))

tensor = torch.tensor([1, 2, 3])
tensor2 = torch.reshape(tensor, (3, 1))

print(tensor, '\n',tensor2)

tensor([1, 2, 3]) 
 tensor([[1],
        [2],
        [3]])


In [60]:
# Tensor.view(shape)
tensor = torch.tensor([1, 2, 3])
print(tensor, '\n', tensor.view(3, 1))

tensor([1, 2, 3]) 
 tensor([[1],
        [2],
        [3]])


In [61]:
# torch.stack([lista_tensores], dim=0)

tensor  = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

tensor3 = torch.stack([tensor, tensor2], dim=0)

print(tensor3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [62]:
# tensor.squeeze(input)

tensor = torch.rand(3, 1, 4, 1, 3)
tensor = torch.squeeze(tensor)
print(tensor.shape)

torch.Size([3, 4, 3])


In [ ]:
#torch.permutate(tensor, reshape)

x = torch.randn(2, 3, 4)
y = torch.permute(x, (0, 2, 1))  # troca eixos 1 e 2

print(x, '\n')
print(y)

tensor([[[ 0.6872, -1.0892, -0.3553, -0.9138],
         [-0.6581,  0.0780,  0.5258, -0.4880],
         [-0.1973, -1.0546,  1.2780,  0.1453]],

        [[ 0.2311,  0.0087, -0.1423,  0.1971],
         [-0.6417, -2.2064, -0.7508,  2.8140],
         [ 0.3598, -0.0898,  0.4584, -0.5644]]]) 

tensor([[[ 0.6872, -0.6581, -0.1973],
         [-1.0892,  0.0780, -1.0546],
         [-0.3553,  0.5258,  1.2780],
         [-0.9138, -0.4880,  0.1453]],

        [[ 0.2311, -0.6417,  0.3598],
         [ 0.0087, -2.2064, -0.0898],
         [-0.1423, -0.7508,  0.4584],
         [ 0.1971,  2.8140, -0.5644]]])


<hr>
<h2>Integração Numpy e PyTorch</h2>

Para transformar Tensores em numpy Array e vice-versa, as funções são:

<ol>
    <li>torch.from_numpy(tensor) -> Array para Tensor</li>
    <br>
    <li>torch.Tensor.numpy()     -> Tensor para Array</li>
</ol>

Pode-se criar tensores aleatorios utilizando:

- torch.rand() -> só positivos
- torch.randn()-> positivos e negativos

In [64]:
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
print(array, '\n', array.dtype)
print()
print(tensor, '\n', tensor.dtype)

[1 2 3 4 5 6 7] 
 int64

tensor([1, 2, 3, 4, 5, 6, 7]) 
 torch.int64


---

# Reprodutibilidade(seed)

Redes neurais começam com números aleatórios para descrever padrões nos dados (esses números são descrições ruins) e tentam melhorar esses números aleatórios usando operações tensorais (e algumas outras coisas que ainda não discutimos) para descrever melhor os padrões nos dados.

Resumidamente:

comece com números aleatórios -> operações de tensor -> tente melhorar (de novo e de novo e de novo)

Embora a aleatoriedade seja agradável e poderosa, às vezes você gostaria que houvesse um pouco menos de aleatoriedade.

Por que?

Assim, você pode realizar experimentos repetíveis.

Por exemplo, você cria um algoritmo capaz de atingir desempenho X.

E então seu amigo experimenta para verificar se você não está louco.

Como eles puderam fazer uma coisa dessas?

É aí que entra a reprodutibilidade.

Em outras palavras, você pode obter os mesmos resultados (ou muito semelhantes) em seu computador executando o mesmo código que eu obtenho no meu?

Vejamos um breve exemplo de reprodutibilidade no PyTorch.

Começaremos criando dois tensores aleatórios, já que são aleatórios, você esperaria que fossem diferentes, certo?

Assim como você esperava, 2 tensores gerados aleatoriamente apresentam valores diferentes.

Mas e se você quisesse criar dois tensores aleatórios com os mesmos valores. Tipo, os tensores ainda conteriam valores aleatórios, mas seriam os mesmos.

É aí que entra torch.manual_seed(seed), onde seed é um número inteiro (como 42, mas pode ser qualquer coisa) que dá sabor à aleatoriedade.

Vamos experimentar criando alguns tensores aleatórios com mais sabores.

In [65]:
RAMDOM_SEED = 42
torch.manual_seed(RAMDOM_SEED) # Graças ao set da seed, o resultado é sempre o mesmo

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C, '\n', random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


# GPU

Para treinar uma IA o ideal é ter acesso a uma GPU(unidade de processamento gráfico). como Os da Nvidea são os mais populares, pode-se verificar se o computador tem uma GPU com:

torch.cuda.is_available()

e para vê se o Pytorch tem acesso à GPU, usa-se o comando

torch.cuda.is_available()
<br>
A saida deve ser: True

In [67]:
torch.cuda.is_available()

True

## Rodando o código na GPU

por padrão, os códigos rodam na CPU, então precisamos colocar ela pra rodar na GPU, mas como?

In [73]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device) # Roda na CPU por padrão

if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


Voltando para CPU

Numpy só consegue lidar com dados que estão na CPU, então é importante trazer os dados de volta para CPU em algum momento. Para fazer isso, deve-se usar:

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
- .cpu() → **copia** o tensor para a memória da CPU
- .numpy() → converte o tensor CPU em array NumPy